---
title: "Harmonizing and standardizing a species names list"
author: "Mysteriarcha"
date: "`r Sys.Date()`"
output: 
  html_document:
    theme: united
    code_folding: show
    code_summary: "Show code"
    code_tools: true
    code_line_numbers: true
    code_overflow: scroll
    toc: true
    toc_depth: 2
    toc_float:
      collapsed: false
      smooth_scroll: false
    number_sections: true
    fig_captions: true
    highlight: tango
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Introduction

Ecology has the peculiarity that it must keep the identity of its study objects.
In vegetation ecology, these are traditionally the species that belong to a species 
pool whose ordination along environmental gradients is of interest to the ecologist.

Ecological datasets, however, often face the problem of coming from different sources
(authors, regions and dates) and hence offering a series of difficulties on the 
harmonization of species names. These difficulties can come mainly in three ways:

1. Just errors when recording the species names in the field. These can be either
typos (for instance, the typo _Teuchrium camaedrys_ instead of _Teucrium chamaedrys_),
which can be easy to solve with some manual data exploration and cleaning, or they
can be real misnamings that can be much harder to solve due to the uncertainity 
they introduce (for example, if we find _Pinus abies_, was the intended name _Picea abies_
or some _Pinus_ species?). In the latter case we would probably have to get in touch
(if possible) with the original author, or at worst guess from contextual information;
we will not deal with such instances here.

2. Taxonomic changes: Having the same species that different authors call
with different names, depending on the region and _Inula salicina_ $\equiv$ _Pentanema salicinum_

3. Systematic changes: Displacements of a species within the phylogenetic tree,
with the consequent change in names. For example, _Dorycnium austriacum_ can be
replaced as _Lotus dorycnium_.



# Including Plots
